#%RAML 1.0
title: bestel-rest-api
baseUri: https://{host}/api/{version}
mediaType:
  - application/json
version: "1"
protocols:
  - HTTPS
  - HTTP
documentation:
  -
    content: "API perrona bien chingona y que chingue su madre el america "
    title: Home