#%RAML 1.0
title: bestel-rest-api
baseUri: https://{host}/api/{version}
mediaType:
  - application/json
version: "1"
protocols:
  - HTTPS
  - HTTP
documentation:
  -
    content: "API perrona bien chingona y que chingue su madre el america "
    title: Home

traits:
  hasRequestID: !include exchange_modules/702f7afc-d4ce-4692-8c4e-a0418d451c60/bearer-token-id/1.0.0/bearer-token-id.raml


/orbit/coverage/orbit:
  is:
    - hasRequestID
  get:
    displayName: ORBIT
    description: "Este endpoint devuelve la cobertura relacionada con una coordenada geográfica."
    queryParameters:
      lat:
        type: number
        required: true
        example: 19.42851
      lng:
        type: number
        required: true
        example: -106.448250
    responses:
      400:
        body:
          application/json:
            example: !include responses/error/400.json
      "200":
        body:
          application/json:
            example: !include responses/orbit/coverage/coverageArray.json
            type: !include data-types/response/orbit/coverage/coverageResponseDT.raml

/orbit/coverage/ping:
  is:
    - hasRequestID
  get:
    displayName: ORBIT PING
    description: "Este endpoint devuelve si esta activo el servicio."
    
    responses:
      400:
        body:
          application/json:
            example: !include responses/error/400.json
      "200":
        body:
          application/json:
            example: !include responses/orbit/ping/pingObject.json
            type: !include data-types/response/orbit/ping/pingResponse.raml





types:
  anillosListaReponse: !include data-types/response/m6/getAnillosListaReponse.raml
  parametrosGeneralesDeAnilloResponse: !include data-types/response/m6/getParametrosGeneralesDeAnilloResponse.raml
  networkLocationsResponse: !include data-types/response/m6/getNetworkLocationsResponse.raml
  conteoEquiposPorAnilloResponse: !include data-types/response/m6/getConteoEquiposPorAnilloResponse.raml
  disponibilidadPuertosPorAnilloResponse: !include data-types/response/m6/getDisponibilidadPuertosPorAnilloResponse.raml

/m6/getParametrosGeneralesDeAnillo:
  displayName: GetParametrosGeneralesDeAnillo
  description: |
    Este endpoint devuelve los parámetros generales de un anillo.
  get:
    description: GET - parametrosGeneralesDeAnillo
    queryParameters:
      ns_nm:
        type: string
        required: false
        default: "null"
    responses:
      200:
        body:
          application/json:
            type: parametrosGeneralesDeAnilloResponse
            example: !include responses/m6/getParametrosGeneralesDeAnilloResponse.json

/m6/getNetworkLocations:
  displayName: GetNetworkLocations
  description: |
    Este endpoint devuelve las ubicaciones de red.
  get:
    description: GET - networkLocations
    responses:
      200:
        body:
          application/json:
            type: networkLocationsResponse
            example: !include responses/m6/getNetworkLocationsResponse.json

/m6/getConteoEquiposPorAnillo:
  displayName: GetConteoEquiposPorAnillo
  description: |
    Este endpoint devuelve el conteo de equipos por anillo.
  get:
    description: GET - conteoEquiposPorAnillo
    queryParameters:
      ns_nm:
        type: string
        required: false
        default: "null"
    responses:
      200:
        body:
          application/json:
            type: conteoEquiposPorAnilloResponse
            example: !include responses/m6/getConteoEquiposPorAnilloResponse.json

/m6/getDisponibilidadPuertosPorAnillo:
  displayName: GetDisponibilidadPuertosPorAnillo
  description: |
    Este endpoint devuelve la disponibilidad de puertos por anillo.
  get:
    description: GET - disponibilidadPuertosPorAnillo
    queryParameters:
      ns_nm:
        type: string
        required: false
        default: "null"
    responses:
      200:
        body:
          application/json:
            type: disponibilidadPuertosPorAnilloResponse
            example: !include responses/m6/getDisponibilidadPuertosPorAnilloResponse.json


/m6/getAnillosLista:
  displayName: GetAnillosLista
  description: |
    Este endpoint devuelve un listado de anillos disponibles.
  get:
    description: GET - Listado de anillos disponibles
    responses:
      200:
        body:
          application/json:
            type: anillosListaReponse
            example: !include responses/m6/getAnillosListaResponse.json

/m6/getAnillosPorNetworkLocation:
  displayName: getAnillosPorNetworkLocation
  description: |
    Este endpoint devuelve listado de anillos por locacion de .
  get:
    description: GET - Listado de anillos disponibles
    responses:
      200:
        body:
          application/json:
            type: anillosListaReponse
            example: !include responses/m6/getAnillosListaResponse.json


      