#%RAML 1.0 DataType
types:
  Coverage:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      remarks:
        type: string
      type:
        type: string

  CoverageList:
    type: array
    items: Coverage

  NetworkCoverage:
    type: object
    properties:
      coverage:
        type: CoverageList
      type:
        type: string