#%RAML 1.0 DataType
type: object
properties:
  NS_ID: 
    type: integer
    example: 1000
  NS_NM_SHORT:
    type: string
    example: "ANILLO CH40S"
  NS_NM_LONG:
    type: string
    example: "ANILLO CH40S FRECUENCIA 121.0 THz"
  CNT:
    type: integer
    example: 15
