#%RAML 1.0 DataType

type: object
properties:
  NetworkLocation:
    type: object
    properties:
        LOCATION_ID:
          type: string
          example: "TLLPDF01"
        LOCATION_NAME:
          type: string
          example: "DFB - COMSAT"
        LOCATION_OWNER:
          type: string
          example: "COUBICACION - BTEL"
        EXCHANGE_AREA:
          type: string
          example: "CENTRO"
        CLAVE_EDIFICIO:
          type: string
          example: "NA"
        LAST_MODIFIED_DATE:
          type: string
          example: "05/09/2019"
        LAST_MODIFIED_USERID:
          type: string
          example: "DGONZALS"