#%RAML 1.0 DataType
type: object
properties:
  buscarTelephoneNumber800Response:
    type: object
    properties:
      checkPointID:
        type: integer
        example: 0
      telephone:
        type: object
        properties:
          nbrInvID:
            type: integer
            example: 8074638
          nir:
            type: integer
            example: 800
          serie:
            type: integer
            example: 001
          identText:
            type: string
            example: "8000019782"
          ocnName:
            type: string
            example: "BESTEL"
