#%RAML 1.0 DataType
type: object
properties:
  reserveTnResponse:
    type: object
    properties:
      return:
        type: object
        properties:
          reservationID:
            type: integer
            example: 2040
